/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;
import java.awt.Color;
import java.awt.Image;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author User
 */
public class search_buy extends javax.swing.JFrame {

    /**
     * Creates new form search_buy
     */
    public search_buy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        all = new javax.swing.JPanel();
        titel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        list = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        cart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        search_txt = new javax.swing.JTextField();
        select = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        view = new javax.swing.JToggleButton();
        cart_p = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        all.setLayout(new java.awt.BorderLayout());

        titel.setBackground(new java.awt.Color(85, 74, 87));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Rockwell", 1, 34)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Welcome To Reader Cafe");

        javax.swing.GroupLayout titelLayout = new javax.swing.GroupLayout(titel);
        titel.setLayout(titelLayout);
        titelLayout.setHorizontalGroup(
            titelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel21)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        titelLayout.setVerticalGroup(
            titelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        all.add(titel, java.awt.BorderLayout.PAGE_START);

        list.setBackground(new java.awt.Color(183, 160, 172));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });

        home.setBackground(new java.awt.Color(85, 74, 87));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_m(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jToggleButton1.setText("Log Out");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        cart.setBackground(new java.awt.Color(85, 74, 87));
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_m(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Cart");

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(listLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jToggleButton1)
                .addContainerGap(593, Short.MAX_VALUE))
        );

        all.add(list, java.awt.BorderLayout.LINE_START);

        center.setBackground(new java.awt.Color(0, 51, 255));
        center.setLayout(new java.awt.CardLayout());

        main.setBackground(new java.awt.Color(85, 74, 87));

        search_txt.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        search_txt.setCaretColor(new java.awt.Color(255, 255, 255));
        search_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });

        select.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Type" }));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 195, 167));
        jLabel22.setText("Search by:");
        jLabel22.setToolTipText("");

        search_btn.setBackground(new java.awt.Color(204, 204, 255));
        search_btn.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_36px_1.png"))); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(22, 16, 24));
        jScrollPane3.setForeground(new java.awt.Color(22, 16, 24));

        table.setAutoCreateRowSorter(true);
        table.setBackground(new java.awt.Color(238, 195, 167));
        table.setFont(new java.awt.Font("Ebrima", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book ID", "Author Name", "Language", "Status", "Page Count", "type", "Click for details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(20);
        table.setSelectionBackground(new java.awt.Color(22, 16, 24));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        panel.setBackground(new java.awt.Color(85, 74, 87));

        jButton1.setBackground(new java.awt.Color(238, 195, 167));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Shopping_Cart_48px_2.png"))); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        desc.setBackground(new java.awt.Color(255, 231, 216));
        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 195, 167));
        jLabel3.setText("Price:");

        id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        id.setForeground(new java.awt.Color(238, 195, 167));
        id.setText("ID");

        s.setBackground(new java.awt.Color(238, 195, 167));
        s.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        s.setForeground(new java.awt.Color(238, 195, 167));
        s.setText("Book Description:");

        name.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(238, 195, 167));
        name.setText("book name");

        price.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("0");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price)
                                .addGap(82, 82, 82)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s))))
                .addGap(80, 80, 80))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(price)
                    .addComponent(id))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        view.setBackground(new java.awt.Color(204, 204, 255));
        view.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        view.setText("View All Books");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel22)
                        .addGap(48, 48, 48)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(search_txt)
                        .addGap(43, 43, 43)
                        .addComponent(search_btn)
                        .addGap(105, 105, 105)
                        .addComponent(view))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        center.add(main, "card2");

        jPanel1.setBackground(new java.awt.Color(85, 74, 87));

        table2.setBackground(new java.awt.Color(238, 195, 167));
        table2.setFont(new java.awt.Font("Eras Demi ITC", 0, 15)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Book name", "Author", "Type", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setRowHeight(25);
        table2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table2);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-macbook-money-24.png"))); // NOI18N
        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("total price is:");

        jPanel2.setBackground(new java.awt.Color(183, 160, 172));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Card Type:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Card number:");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa card", "Debit card", "Credit card" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Full name:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Shipping Address:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("security code:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(66, 66, 66)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        total.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 195, 167));
        jLabel10.setText("payment information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout cart_pLayout = new javax.swing.GroupLayout(cart_p);
        cart_p.setLayout(cart_pLayout);
        cart_pLayout.setHorizontalGroup(
            cart_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cart_pLayout.setVerticalGroup(
            cart_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        center.add(cart_p, "card3");

        all.add(center, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed

    }//GEN-LAST:event_selectActionPerformed
int row = 0;//row
int total_price=0;
int num_book=0;
int[] buy_id = null;
    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String o = null;
        for(int r = 0 ; r < 100 ; r++){
            for(int c = 0 ; c < 8 ; c++)
            table.setValueAt(o,r,c);

            try {
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String url = "jdbc:oracle:thin:@localhost:1521:orcl";
                Connection con = DriverManager.getConnection(url, "myPROJuser", "654321");
                if (select.getSelectedIndex() == 0) {
                    String sql = "select b.book_name,b.book_id,z.author_name,b.status,b.pagecount,b.typeofbook,b.language FROM book b, authorbook x, author z where b.book_id = x.book_id and x.author_id = z.author_id and b.book_name = ?";
                    PreparedStatement s;
                    s = con.prepareStatement(sql);
                    s.setString(1, search_txt.getText());
                    ResultSet rs = s.executeQuery();
                    int row = 0;//row
                    int column;//column
                    while (rs.next()) {
                        column = 0;
                        String bookName = rs.getString(1);
                        table.setValueAt(bookName, row, column);
                        column++;
                        BigDecimal id = new BigDecimal(rs.getString(2));
                        table.setValueAt(id, row, column);
                        column++;
                        String authorName = rs.getString("author_name");
                        table.setValueAt(authorName, row, column);
                        column++;
                        
                        String language = rs.getString("language");
                        table.setValueAt(language, row, column);
                        column++;
                        String status = rs.getString("status");
                        table.setValueAt(status, row, column);
                        column++;
                        BigDecimal count = new BigDecimal(rs.getString(5));
                        table.setValueAt(count, row, column);
                        column++;
                        String type = rs.getString("typeofbook");
                        table.setValueAt(type, row, column);
row++;
                    }
                } else if (select.getSelectedIndex() == 1) {
                    String sql = "select b.book_name,b.book_id,z.author_name,b.status,b.pagecount,b.typeofbook,b.language FROM book b, authorbook x, author z where b.book_id = x.book_id and x.author_id = z.author_id and z.author_name = ?";
                    PreparedStatement s;
                    s = con.prepareStatement(sql);
                    s.setString(1, search_txt.getText());
                    ResultSet rs = s.executeQuery();
                    int row = 0;//row
                    int column;//column
                    while (rs.next()) {
                        column = 0;
                        String bookName = rs.getString(1);
                        table.setValueAt(bookName, row, column);
                        column++;
                        BigDecimal id = new BigDecimal(rs.getString(2));
                        table.setValueAt(id, row, column);
                        column++;
                        String authorName = rs.getString("author_name");
                        table.setValueAt(authorName, row, column);
                        column++;
                        
                        String language = rs.getString("language");
                        table.setValueAt(language, row, column);
                        column++;
                        String status = rs.getString("status");
                        table.setValueAt(status, row, column);
                        column++;
                        BigDecimal count = new BigDecimal(rs.getString(5));
                        table.setValueAt(count, row, column);
                        column++;
                        String type = rs.getString("typeofbook");
                        table.setValueAt(type, row, column);
                        row++;
                    }
                } else if (select.getSelectedIndex() == 2) {
                    String sql = "select b.book_name,b.book_id,z.author_name,b.status,b.pagecount,b.typeofbook,b.language FROM book b, authorbook x, author z where b.book_id = x.book_id and x.author_id = z.author_id and b.typeofbook = ?";
                    PreparedStatement s;
                    s = con.prepareStatement(sql);
                    s.setString(1, search_txt.getText());
                    ResultSet rs = s.executeQuery();
                    int row = 0;//row
                    int column;//column
                    while (rs.next()) {
                        column = 0;
                        String bookName = rs.getString(1);
                        table.setValueAt(bookName, row, column);
                        column++;
                        BigDecimal id = new BigDecimal(rs.getString(2));
                        table.setValueAt(id, row, column);
                        column++;
                        String authorName = rs.getString("author_name");
                        table.setValueAt(authorName, row, column);
                        column++;
                        
                        String language = rs.getString("language");
                        table.setValueAt(language, row, column);
                        column++;
                        String status = rs.getString("status");
                        table.setValueAt(status, row, column);
                        column++;
                        BigDecimal count = new BigDecimal(rs.getString(5));
                        table.setValueAt(count, row, column);
                        column++;
                        String type = rs.getString("typeofbook");
                        table.setValueAt(type, row, column);
                        row++;
                    }

                }
                con.commit();
                con.close();

            } catch (SQLException ex) {
                //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.toString());
            }

        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        buy book =new buy( );
        int i =table.getSelectedRow();
        TableModel model=table.getModel();
        id.setText((String) model.getValueAt(i, 1));
        name.setText((String) model.getValueAt(i, 0));
        BigDecimal b_id = new BigDecimal (id.getText());
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con = DriverManager.getConnection(url,"myPROJuser","654321");
            Statement s;
            s = con.createStatement();
            String sql="select * from book where book_id = "+b_id+" ";
            String description=null;
            String b_price = null;
            String image=null;
            ResultSet rs= s.executeQuery(sql);
            if(rs.next()){
                description=rs.getString("description");
                //b_price=rs.getString("price");
                b_price=String.valueOf(rs.getInt("price"));
                image=rs.getString("image");
                desc.setText(description);
                price.setText(b_price);
                //this generates an image file
                ImageIcon icon = new ImageIcon(image);
                pic.setIcon(icon);
            }

        } catch (SQLException ex) {
            Logger.getLogger(search_buy.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tableMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dm = (DefaultTableModel)table.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(0);
        }

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con = DriverManager.getConnection(url,"myPROJuser","654321");
            Statement s;
            s = con.createStatement();
            String sql= "select * from  author a ,book b ,authorbook z where a.author_id = z.author_id and b.book_id=z.book_id ";
            ResultSet rs= s.executeQuery(sql);
            while(rs.next()){
                String name=rs.getString("book_name");
                String type=rs.getString("typeofbook");
                String lang=rs.getString("language");
                String status=rs.getString("status");
                String id=String.valueOf(rs.getInt("book_id"));
                String page=String.valueOf(rs.getInt("pagecount"));
                String author=rs.getString("author_name");
               
                //String sql2= "select a.author_name from author a ,book b ,authorbook z where a.author_id = z.author_id and b.book_id = "+id+"";

                // ResultSet rs2=s.executeQuery(sql2);

                String tableData[] ={name,id,author,lang,status,page,type,"Click to view"};
                DefaultTableModel model = (DefaultTableModel)table.getModel();
                model.addRow(tableData);

            }

        } catch (SQLException ex) {
            Logger.getLogger(search_buy.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thanks For Visiting Our Site");
        new Front_page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
     
        
        
    }//GEN-LAST:event_listMouseClicked

    private void home_m(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_m
        // TODO add your handling code here:
           if(evt.getSource()==home){
        main.setVisible(true);
        cart_p.setVisible(false);
        }
        
        
    }//GEN-LAST:event_home_m

    private void cart_m(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_m
        // TODO add your handling code here:
         if(evt.getSource()==cart){
        main.setVisible(false);
        cart_p.setVisible(true);
        }
    }//GEN-LAST:event_cart_m

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setBackground(new Color(85, 74, 87));
    }//GEN-LAST:event_homeMouseEntered

    private void cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseEntered
        // TODO add your handling code here:
        cart.setBackground(new Color(85, 74, 87));
    }//GEN-LAST:event_cartMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
         home.setBackground(new Color(102, 89, 104));
    }//GEN-LAST:event_homeMouseExited

    private void cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseExited
        // TODO add your handling code here:
         cart.setBackground(new Color(102, 89, 104));
    }//GEN-LAST:event_cartMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user_id=account.getuser();
        String v="not available";
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con = DriverManager.getConnection(url,"myPROJuser","654321");
            Statement s;
            s = con.createStatement();
             BigDecimal book_id = new BigDecimal(id.getText());
             String sql= "select * from  author a ,book b ,authorbook z where a.author_id = z.author_id and b.book_id=z.book_id and b.book_id="+book_id+"";
            ResultSet rs= s.executeQuery(sql);
            
                    int column;//column
                    while (rs.next()) {
                        column = 0;
                        int id=(rs.getInt("book_id"));
                        table2.setValueAt(id, row, column);
                        column++;
                         String name = rs.getString("book_name");
                        table2.setValueAt(name, row, column);
                        column++;
                        String authorName = rs.getString("author_name");
                        table2.setValueAt(authorName, row, column);
                        column++;
                       
                        String type = rs.getString("typeofbook");
                        table2.setValueAt(type, row, column);
                        column++;
                        int price=(rs.getInt("price"));
                        table2.setValueAt(price, row, column);
                        row++;
                       total_price += price;
            total.setText(String.valueOf(total_price));
            num_book++;
            String sql2= "insert into bought values ("+id+" ,"+price+",'"+user_id+"', '"+name+"' ) ";
            s.executeQuery(sql2);
            String sql3= "UPDATE book SET num_copies = num_copies-1  WHERE book_id = "+book_id+"";
            String sql4= "UPDATE customer SET num_of_books = num_of_books+1  WHERE customer_id = '"+user_id+"'";
            String sql5= "UPDATE customer SET total_payment = total_payment+ "+total_price+" WHERE customer_id = '"+user_id+"'";
            s.executeUpdate(sql3);
            s.executeUpdate(sql4);
            s.executeUpdate(sql5);
            if(rs.getInt("num_copies")==0){
            String sql6= "UPDATE book SET status= '"+v+"'";
             s.executeUpdate(sql6);
            
            }
             con.commit();
            con.close();
            //buy_id[num_book]=id;
                    }
        } catch (SQLException ex) {
            Logger.getLogger(search_buy.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        JOptionPane.showMessageDialog(this , "added to the shopping cart");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String user_id=account.getuser();
        BigDecimal the_id;
        String v="not available";
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con = DriverManager.getConnection(url,"myPROJuser","654321");
            Statement s;
            s = con.createStatement();
           if(t1.getText()==null||t2.getText()==null||t3.getText()==null||t4.getText()==null||t5.getText()==null||t6.getText()==null||t7.getText()==null){
                JOptionPane.showMessageDialog(this , "you must full all the info!");
            }
            else{
               JOptionPane.showMessageDialog(this , "your order is compleate");
           }
           /*int j=0;
            for(int i=num_book;i>=0;i--){
                the_id= new BigDecimal(  (String) table2.getValueAt(j,0));
                String book="select * from book where book_id= "+the_id+" ";
             ResultSet rs= s.executeQuery(book); 
            if(rs.next()){ 
                String name= rs.getString("book_name");
                BigDecimal price= new BigDecimal(rs.getString("price"));
             String sql= "insert into bought values ("+the_id+" ,"+price+",'"+user_id+"', '"+name+" ) ";
            String sql2= "UPDATE book SET num_copies = num_copies-1  WHERE boo_id = "+the_id+"";
            String sql4= "UPDATE customer SET num_of_book = num_of_book+1  WHERE customer_id = "+user_id+"";
           String sql3= "UPDATE customer SET total_payment = total_payment+ "+total_price+" WHERE customer_id = "+user_id+"";
            if(rs.getInt("num_copies")==0){
            
            s.executeUpdate(sql3);
            }
            s.executeUpdate(sql);
            s.executeUpdate(sql2);
            s.executeUpdate(sql4);
            }//}
            j++;
            
            }*/
            
        } catch (SQLException ex) {
            Logger.getLogger(search_buy.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_buy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel all;
    private javax.swing.JPanel cart;
    private javax.swing.JPanel cart_p;
    private javax.swing.JPanel center;
    private javax.swing.JTextArea desc;
    private javax.swing.JPanel home;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel list;
    private javax.swing.JPanel main;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel price;
    private javax.swing.JLabel s;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JPanel titel;
    private javax.swing.JTextField total;
    private javax.swing.JToggleButton view;
    // End of variables declaration//GEN-END:variables
}
